
INST_HALT = 'halt'
INST_PUSH_INT = 'push-int'
INST_PUSH = 'push'
INST_INC_TOP = 'inc-top'
INST_MUL = 'mul'
INST_ADD = 'add'
INST_SUB = 'sub'
INST_DIV = 'div'
INST_IDIV = 'idiv'
INST_LSH = 'lsh'
INST_RSH = 'rsh'
INST_AND = 'and'
INST_OR = 'or'
INST_XOR = 'xor'
INST_MOD = 'mod'
INST_POW = 'pow'

# unary operators
INST_INC = 'inc'
INST_DEC = 'dec'
INST_NOT = 'not'
INST_NEG = 'neg'
INST_ABS = 'abs'

INST_TEST = 'test'
INST_POP = 'pop'
INST_JPLT = 'jplt'
INST_JPLE = 'jple'
INST_JPGT = 'jpgt'
INST_JPGE = 'jpge'
INST_JPEQ = 'jpeq'
INST_JPNE = 'jpne'
INST_ERROR = 'error'
INST_EXIT = 'exit'
INST_DEC_TOP = 'dec-top'
INST_PRINT_TOP = 'print-top'
INST_PRINT = 'print'
INST_TEST_TOP = 'test-top'
INST_CALL = 'call'
INST_RET = 'ret'
INST_JUMP = 'jump'
INST_PRINTLN = 'println'
INST_PRINTLN_TOP = 'println-top'
INST_READ = 'read'
INST_READ_INT = 'read-int'

INST_INT = 'int'

VIR_INST_LABEL = 'label'
